### ISSUE TITLE
Tag and release

### ISSUE THREAD

**Issue by philoserf** [alertlogic/al_agents#12]
Please lets start, at minimum, start tagging in sync with the cookbook metadata version. A github release with release notes included are then the shiny finish.

**Comment by motobob** [comment]
tagging started

**Comment by philoserf** [comment]
This issue should be reopened since the latest "_release_" did not get the git tag or GitHub release treatment.

**Comment by jearly** [comment]
@philoserf I have reopened this issue and agree it should not be closed until the revision has properly been tagged and accompanied by a release.

**Comment by philoserf** [comment]
@jearly Actually version 0.4.0 was tagged and released after I opened #12. You may close this.

I opened #26 to cover the two newer releases that went out tag-less and release-less.

**Comment by jearly** [comment]
@philoserf Thank you.
