### ISSUE TITLE
Add al_agent to supermarket

### ISSUE THREAD

**Issue by philoserf** [alertlogic/al_agents#13]
As a user of the al_agent cookbook
I want to reference al_agent in `metadata.rb`
And I do not want to reference the github location in `Berksfile`
So that it is very easy to use the al_agent cookbook

Today I must have a `depends 'al_agent', '~> 0.3'` in my metadata.rb
And I must have `cookbook 'al_agents', git: 'https://github.com/alertlogic/al_agents.git', tag: 'v0.3.0'`

If al_agent cookbook were loaded into the supermarket
Then only the entry in `metadata.rb` would be required.

https://supermarket.chef.io/cookbooks?q=al_agent

**Comment by motobob** [comment]
agree. 
The feature request for supermarket support is being investigated and hopefully will be addressed

**Comment by spuder** [comment]
+1 

It would be nice if it was searchable by name 'alert logic' instead of 'al_agent'

**Comment by infernokodiak** [comment]
Hi all, The cookbook is now shared in the chef supermarket and searchable by 'alert logic'

https://supermarket.chef.io/cookbooks?utf8=%E2%9C%93&q=alert+logic&platforms%5B%5D=

**Comment by philoserf** [comment]
Thank you.
