### ISSUE TITLE
Is windows supported

### ISSUE THREAD

**Issue by spuder** [alertlogic/al_agents#22]
The readme doesn't specify windows as being supported, however there does appear to be a windows recipe. 

Is windows supported? If so, which versions are tested?

**Comment by philoserf** [comment]
I do not know a definitive answer to your question but u wanted to let you know I've just started to add test-kitchen support. I will, of course, offer a pull request with that support once I've got it in shape. 

I'll be assuming support for all windows versions supported by al_agent-LATEST.msi and adding tests for those windows versions.

**Comment by philoserf** [comment]
http://docs.alertlogic.com/content/docs/install_and_configure/agents/agentopsupp.htm

Agent supported platforms

**Comment by philoserf** [comment]
See https://docs.chef.io/supported_platforms.html

For chef-client supported platforms

**Comment by spuder** [comment]
Yes, I see that chef and alert logic support windows. I have alert logic running on my windows servers. I'm curious if the cookbook works with windows hosts.

**Comment by philoserf** [comment]
I have successfully used the windows recipe.

**Comment by spuder** [comment]
Thanks, It will be a few days before I can test this.

**Comment by jearly** [comment]
@spuder I assume you have successfully used this cookbook on windows. If you have any issues, let us know and we can reopen, but windows deployments should be fully supported.
