### ISSUE TITLE
Question - Can cookbook change egress_url?

### ISSUE THREAD

**Issue by spuder** [alertlogic/al_agents#46]
By default the msi configures to log to the following egress_url

        "egress_url": "https://vaporator.alertlogic.com:443"

Is there a way to change that later; maybe with an environment variable or config file? Or are you expected to destroy and recreate your nodes?

**Comment by jearly** [comment]
@spuder You can change this setting with the following methods:

### Linux:
/etc/init.d/al-agent configure --host ... --port ...
/etc/init.d/al-agent restart

### Windows:
%ProgramFiles(x86)%\AlertLogic\al-agent.exe configure --host ... --port ...
sc.exe stop al_agent
sc.exe start al_agent

Re-installing from package (giving it different parameters) would also work, even on top of an existing install

You can also change the egress_url in a wrapper cookbook by specifying the egress attribute in your recipe:
```
node.normal['al_agents']['agent']['egress_url'] = "http(s)://{preferred-url-here:preferred-port}"
```

**Comment by spuder** [comment]
Thanks, I have the egress set in my role. I am using windows. 

I don't think that there is a way to reinstall from the package, since there is a guard making the installation idempotent. 

https://github.com/alertlogic/al_agents/blob/master/recipes/_windows.rb#L20

**Comment by jearly** [comment]
Agreed. The re-install would either have to be manually done or you would have to include logic in a wrapper recipe to remove the package prior to running the al_agents cookbook to reinstall/configure the package. Perhaps we could add this re-installation option as a feature in future releases.

**Comment by spuder** [comment]
Yes, that would be nice. 
If the cookbook were converted to a library cookbook, I suspect it might be easier to put a guard so that if node['al_agents']['agent']['egress_url'] is updated, then to notify an exec to run `%ProgramFiles(x86)%\AlertLogic\al-agent.exe configure --host ... --port ...`
