### ISSUE TITLE
Package Install Only Option

### ISSUE THREAD

**Issue by bcg** [alertlogic/al_agents#54]
We use Chef to build our AMIs and only want to install the al_agent package (not to configure or provision). We will handle configuration and provisioning at boot time. We hacked this into a forked repo (`al_agents::package`), but it would be nice to have this option available in the main cookbook.

**Comment by jearly** [comment]
Hello @bcg,

Did you try to use the for_imaging attribute already in the cookbook? It should allow you to install the package and bypass the provisioning step. This feature was intended for users who want to create idempotent images: 

['al_agents']['agent']['for_imaging'] - The for_imaging attribute determines if the install process will continue or stop prior to provisioning. If the for_imaging attribute is set to true then the install process perform an install only and stop before provisioning. This allows for instance snapshots to be saved and started for later use. With this attribute set to false then the provisioning process is performed during setup. Boolean defaults to false.

https://github.com/alertlogic/al_agents/blob/master/attributes/default.rb#L9

**Comment by bcg** [comment]
That was the first thing we tried but as you can see [here](https://github.com/alertlogic/al_agents/blob/51b77990e68a275ef568617c1e265c206327598b/recipes/install.rb#L31) the same cookbook that installs the package also runs the configure and provision step. As far as I can tell `for_imaging` just keeps it from [starting](https://github.com/alertlogic/al_agents/blob/51b77990e68a275ef568617c1e265c206327598b/recipes/_linux.rb).

**Comment by jearly** [comment]
@bcg I see. I missed that detail in your original request. Yes. the for_imaging option only prevents the agent from starting. We will make sure to update the cookbook with a proper attribute to 'install only' when set.
